### ISSUE TITLE
Pasting doesn't work

### ISSUE THREAD

**Issue by IvanAli** [denis-ryzhkov/mc_xclip#1]
Took me hours to realize this script was the reason Ctrl-V did not always work in Ubuntu when xclip was installed too

A solution to syncronize mcedit with the system clipboard is to modify the following in the ~/.config/mc/ini file:

clipboard_store=xclip -i -selection clipboard
clipboard_paste=xclip -o -selection clipboard

**Comment by denis-ryzhkov** [comment]
Thank you very much, @IvanAli !

I had NO problems with Ctrl-V, but was unhappy with disk-based sync.

Now I finally deprecated "mc_xclip" and published new instructions everywhere:
* https://github.com/denis-ryzhkov/mc_xclip
* https://pypi.python.org/pypi/mc_xclip
